# imports:
#     - php

# filter:
#     excluded_paths: [vendor/*, test/*]

# build:
#     nodes:
#         my-tests:
#             environment:
#                 php:
#                     version: 8.1
#         analysis:
#             tests:
#                 override:
#                     - php-scrutinizer-run
#     tests:
#         override:
#             -
#                 # command: "composer phpunit"
#                 command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
#                 coverage:
#                     file: "build/coverage.clover"
#                     format: "php-clover"


build:
    nodes:
        analysis:
            project-setup:
                override:
                    -'true'
            tests:
                override:
                    -php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
                    -js-scrutinizer-run
        tests: true

    filter:
        excluded_paths: 
            - 'tests'/*
            - 'bin/*'
            - 'tools/*'
            - '*.min.js'
            - '/vendor/*'
            - 'build/*'
        dependency-paths:
            -'tools/*'
    checks:
        php: true
        javascript: true
    coding-style:
        php:
            spaces:
                around_operators:
                    bitwise: false
                other:
                    after_type_cast: false
